/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Custom
 */
interface Custom {
  /** Error code */
  error: string;
  /** Human-readable error message */
  message: string;
  /** Additional error details */
  details?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export class CustomError extends ApiError<Custom> {}
