/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import { DeliveryDetails, deliveryDetailsSchema } from '../deliveryDetails.js';

/** This is a container type for one-of types. */
export type FulfillmentCallbackDeliveryDetails = string | DeliveryDetails;

export const fulfillmentCallbackDeliveryDetailsSchema: Schema<FulfillmentCallbackDeliveryDetails> = lazy(
  () => oneOf([string(), deliveryDetailsSchema])
);

export namespace FulfillmentCallbackDeliveryDetails {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }

  /**
   * Validation method to narrow down union type to DeliveryDetails type case.
   *
   * This is DeliveryDetails case.
   */
  export function isDeliveryDetails(value: unknown): value is DeliveryDetails {
    return isMappedValueValidForSchema(value, deliveryDetailsSchema);
  }
}
