/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  InventoryStockDecreaseEvent,
  inventoryStockDecreaseEventSchema,
} from '../inventoryStockDecreaseEvent.js';
import {
  InventoryStockDepletedEvent,
  inventoryStockDepletedEventSchema,
} from '../inventoryStockDepletedEvent.js';
import {
  InventoryStockIncreaseEvent,
  inventoryStockIncreaseEventSchema,
} from '../inventoryStockIncreaseEvent.js';

/** This is a container type for one-of types. */
export type InventoryChangeEventBody =
  | InventoryStockIncreaseEvent
  | InventoryStockDecreaseEvent
  | InventoryStockDepletedEvent;

export const inventoryChangeEventBodySchema: Schema<InventoryChangeEventBody> = lazy(
  () =>
    oneOf([
      inventoryStockIncreaseEventSchema,
      inventoryStockDecreaseEventSchema,
      inventoryStockDepletedEventSchema,
    ])
);

export namespace InventoryChangeEventBody {
  /**
   * Validation method to narrow down union type to InventoryStockIncreaseEvent type case.
   *
   * This is InventoryStockIncreaseEvent case.
   */
  export function isInventoryStockIncreaseEvent(
    value: unknown
  ): value is InventoryStockIncreaseEvent {
    return isMappedValueValidForSchema(
      value,
      inventoryStockIncreaseEventSchema
    );
  }

  /**
   * Validation method to narrow down union type to InventoryStockDecreaseEvent type case.
   *
   * This is InventoryStockDecreaseEvent case.
   */
  export function isInventoryStockDecreaseEvent(
    value: unknown
  ): value is InventoryStockDecreaseEvent {
    return isMappedValueValidForSchema(
      value,
      inventoryStockDecreaseEventSchema
    );
  }

  /**
   * Validation method to narrow down union type to InventoryStockDepletedEvent type case.
   *
   * This is InventoryStockDepletedEvent case.
   */
  export function isInventoryStockDepletedEvent(
    value: unknown
  ): value is InventoryStockDepletedEvent {
    return isMappedValueValidForSchema(
      value,
      inventoryStockDepletedEventSchema
    );
  }
}
