/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  isMappedValueValidForSchema,
  number,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  RootLevelPrimitiveOneOfEventRequest,
  rootLevelPrimitiveOneOfEventRequestSchema,
} from '../rootLevelPrimitiveOneOfEventRequest.js';
import {
  RootLevelPrimitiveOneOfEventRequest1,
  rootLevelPrimitiveOneOfEventRequest1Schema,
} from '../rootLevelPrimitiveOneOfEventRequest1.js';

/** This is a container type for one-of types. */
export type RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody =
  | RootLevelPrimitiveOneOfEventRequest
  | number
  | RootLevelPrimitiveOneOfEventRequest1[]
  | number[];

export const rootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBodySchema: Schema<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody> = oneOf(
  [
    rootLevelPrimitiveOneOfEventRequestSchema,
    number(),
    array(rootLevelPrimitiveOneOfEventRequest1Schema),
    array(number()),
  ]
);

export namespace RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody {
  /**
   * Validation method to narrow down union type to RootLevelPrimitiveOneOfEventRequest type case.
   *
   * This is RootLevelPrimitiveOneOfEvent Request case.
   */
  export function isRootLevelPrimitiveOneOfEventRequest(
    value: unknown
  ): value is RootLevelPrimitiveOneOfEventRequest {
    return isMappedValueValidForSchema(
      value,
      rootLevelPrimitiveOneOfEventRequestSchema
    );
  }

  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Number case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }

  /**
   * Validation method to narrow down union type to RootLevelPrimitiveOneOfEventRequest1[] type case.
   *
   * This is Array of RootLevelPrimitiveOneOfEvent Request1 case.
   */
  export function isArrayOfRootLevelPrimitiveOneOfEventRequest1(
    value: unknown
  ): value is RootLevelPrimitiveOneOfEventRequest1[] {
    if (!Array.isArray(value)) {
      return false;
    }
    return isMappedValueValidForSchema(
      value,
      array(rootLevelPrimitiveOneOfEventRequest1Schema)
    );
  }

  /**
   * Validation method to narrow down union type to number[] type case.
   *
   * This is Array of Number case.
   */
  export function isArrayOfNumber(value: unknown): value is number[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'number')
    );
  }
}
