/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  SystemAlertNotificationEvent,
  systemAlertNotificationEventSchema,
} from '../systemAlertNotificationEvent.js';
import {
  SystemMaintenanceNotificationEvent,
  systemMaintenanceNotificationEventSchema,
} from '../systemMaintenanceNotificationEvent.js';
import {
  SystemPerformanceNotificationEvent,
  systemPerformanceNotificationEventSchema,
} from '../systemPerformanceNotificationEvent.js';

/** This is a container type for one-of types. */
export type SystemNotificationEventBody =
  | SystemAlertNotificationEvent
  | SystemMaintenanceNotificationEvent
  | SystemPerformanceNotificationEvent;

export const systemNotificationEventBodySchema: Schema<SystemNotificationEventBody> = lazy(
  () =>
    oneOf([
      systemAlertNotificationEventSchema,
      systemMaintenanceNotificationEventSchema,
      systemPerformanceNotificationEventSchema,
    ])
);

export namespace SystemNotificationEventBody {
  /**
   * Validation method to narrow down union type to SystemAlertNotificationEvent type case.
   *
   * This is SystemAlertNotificationEvent case.
   */
  export function isSystemAlertNotificationEvent(
    value: unknown
  ): value is SystemAlertNotificationEvent {
    return isMappedValueValidForSchema(
      value,
      systemAlertNotificationEventSchema
    );
  }

  /**
   * Validation method to narrow down union type to SystemMaintenanceNotificationEvent type case.
   *
   * This is SystemMaintenanceNotificationEvent case.
   */
  export function isSystemMaintenanceNotificationEvent(
    value: unknown
  ): value is SystemMaintenanceNotificationEvent {
    return isMappedValueValidForSchema(
      value,
      systemMaintenanceNotificationEventSchema
    );
  }

  /**
   * Validation method to narrow down union type to SystemPerformanceNotificationEvent type case.
   *
   * This is SystemPerformanceNotificationEvent case.
   */
  export function isSystemPerformanceNotificationEvent(
    value: unknown
  ): value is SystemPerformanceNotificationEvent {
    return isMappedValueValidForSchema(
      value,
      systemPerformanceNotificationEventSchema
    );
  }
}
