/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  UserActionNotificationEvent,
  userActionNotificationEventSchema,
} from '../userActionNotificationEvent.js';
import {
  UserPreferenceNotificationEvent,
  userPreferenceNotificationEventSchema,
} from '../userPreferenceNotificationEvent.js';
import {
  UserStatusNotificationEvent,
  userStatusNotificationEventSchema,
} from '../userStatusNotificationEvent.js';

/** This is a container type for one-of types. */
export type UserNotificationEventBody =
  | UserActionNotificationEvent
  | UserStatusNotificationEvent
  | UserPreferenceNotificationEvent;

export const userNotificationEventBodySchema: Schema<UserNotificationEventBody> = lazy(
  () =>
    oneOf([
      userActionNotificationEventSchema,
      userStatusNotificationEventSchema,
      userPreferenceNotificationEventSchema,
    ])
);

export namespace UserNotificationEventBody {
  /**
   * Validation method to narrow down union type to UserActionNotificationEvent type case.
   *
   * This is UserActionNotificationEvent case.
   */
  export function isUserActionNotificationEvent(
    value: unknown
  ): value is UserActionNotificationEvent {
    return isMappedValueValidForSchema(
      value,
      userActionNotificationEventSchema
    );
  }

  /**
   * Validation method to narrow down union type to UserStatusNotificationEvent type case.
   *
   * This is UserStatusNotificationEvent case.
   */
  export function isUserStatusNotificationEvent(
    value: unknown
  ): value is UserStatusNotificationEvent {
    return isMappedValueValidForSchema(
      value,
      userStatusNotificationEventSchema
    );
  }

  /**
   * Validation method to narrow down union type to UserPreferenceNotificationEvent type case.
   *
   * This is UserPreferenceNotificationEvent case.
   */
  export function isUserPreferenceNotificationEvent(
    value: unknown
  ): value is UserPreferenceNotificationEvent {
    return isMappedValueValidForSchema(
      value,
      userPreferenceNotificationEventSchema
    );
  }
}
