/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpRequest } from '../../core';
import { JSONBig } from '../../jsonBigInt';
import { validateAndMap } from '../../schema';
import { createUnknownEvent } from '../unknownEvent';
import { webhooksNoVerificationEventParsingResultSchema } from './webhooksNoVerificationEventParsingResult';
import { WebhooksNoVerificationParsingResult } from './webhooksNoVerificationParsingResult';

/** Demo group with no payload verification (unsigned webhooks). */
export class WebhooksNoVerificationHandler {
  /**
   * Parses the webhook event from the incoming request.
   *
   * @param request The incoming HttpRequest
   * @returns WebhookEventParsingResult if valid, UnknownEvent otherwise
   */
  public parseEvent(request: HttpRequest): WebhooksNoVerificationParsingResult {
    const requestBody = request.body;

    if (requestBody === undefined) {
      return createUnknownEvent('Missing request body');
    }
    if (requestBody.type !== 'text') {
      return createUnknownEvent('Invalid request body type');
    }

    try {
      const parsedRequestBody = JSONBig.parse(requestBody.content);

      const validationResult = validateAndMap(
        parsedRequestBody,
        webhooksNoVerificationEventParsingResultSchema
      );

      if (validationResult.errors) {
        return createUnknownEvent(requestBody.content);
      }

      return validationResult.result;
    } catch (error) {
      return createUnknownEvent(requestBody.content);
    }
  }
}
