/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isSignatureVerificationResult,
  SignatureVerificationFailure,
} from '../../core';
import { InventoryChangeEventBody } from '../../models/containers/inventoryChangeEventBody';
import { SystemNotificationEventBody } from '../../models/containers/systemNotificationEventBody';
import { UserNotificationEventBody } from '../../models/containers/userNotificationEventBody';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { WebhooksBEventParsingResult } from './webhooksBEventParsingResult';

/**
 * Union type representing all possible cases, handled by WebhooksB handler.
 */
export type WebhooksBParsingResult =
  | WebhooksBEventParsingResult
  | UnknownEvent
  | SignatureVerificationFailure;

export namespace WebhooksBParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: WebhooksBParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down the parsing result
   *
   * to a SignatureVerificationFailure type case.
   */
  export function isSignatureVerificationFailure(
    result: WebhooksBParsingResult
  ): result is SignatureVerificationFailure {
    return isSignatureVerificationResult(result) && result.success === false;
  }

  /**
   * Validation method to narrow down union type to UserNotificationEvent type case.
   *
   * Triggered when user-related notifications occur
   */
  export function isUserNotificationEventEvent(
    result: WebhooksBParsingResult
  ): result is UserNotificationEventBody {
    return WebhooksBEventParsingResult.isUserNotificationEventBody(result);
  }

  /**
   * Validation method to narrow down union type to SystemNotificationEvent type case.
   *
   * Triggered when system-wide notifications occur
   */
  export function isSystemNotificationEventEvent(
    result: WebhooksBParsingResult
  ): result is SystemNotificationEventBody {
    return WebhooksBEventParsingResult.isSystemNotificationEventBody(result);
  }

  /**
   * Validation method to narrow down union type to InventoryChangeEvent type case.
   *
   * Triggered when inventory stock levels change
   */
  export function isInventoryChangeEventEvent(
    result: WebhooksBParsingResult
  ): result is InventoryChangeEventBody {
    return WebhooksBEventParsingResult.isInventoryChangeEventBody(result);
  }
}
