/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, number, oneOf, Schema, string } from '../../schema.js';

/** This is a container type for one-of types. */
export type WebhooksCEventParsingResult =
  | string
  | number
  | number[]
  | Record<string, string>;

export const webhooksCEventParsingResultSchema: Schema<WebhooksCEventParsingResult> = oneOf(
  [string(), number(), array(number()), dict(string())]
);

export namespace WebhooksCEventParsingResult {
  /**
   * Validation method to narrow down union type to string type case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }

  /**
   * Validation method to narrow down union type to number type case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }

  /**
   * Validation method to narrow down union type to number[] type case.
   */
  export function isArrayOfNumber(value: unknown): value is number[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'number')
    );
  }

  /**
   * Validation method to narrow down union type to Record<string, string> type case.
   */
  export function isMapOfString(
    value: unknown
  ): value is Record<string, string> {
    return (
      typeof value === 'object' &&
      value !== null &&
      Object.values(value).every((val) => typeof val === 'string')
    );
  }
}
