/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  HttpRequest,
  SignatureVerificationResult,
  SignatureVerifier,
} from '../../core';
import { HmacSignatureVerifier } from '../../hmacSignatureVerifier';
import { JSONBig } from '../../jsonBigInt';
import { validateAndMap } from '../../schema';
import { createUnknownEvent } from '../unknownEvent';
import { webhooksEventParsingResultSchema } from './webhooksEventParsingResult';
import { WebhooksParsingResult } from './webhooksParsingResult';

/** Standard webhook group for order and payment events */
export class WebhooksHandler {
  private signatureVerifier: SignatureVerifier;

  constructor(secretKey: string) {
    this.signatureVerifier = new HmacSignatureVerifier(
      secretKey,
      'X-Signature',
      (request) => {
        const payload =
          request.body?.type === 'text' ? request.body.content : '';
        const finalMessage = `${payload}`;
        return Buffer.from(finalMessage, 'utf-8');
      },
      'SHA256',
      'hex',
      '{digest}'
    );
  }

  /**
   * Verifies the signature of an incoming webhook request.
   *
   * @param request The incoming HttpRequest
   * @returns      SignatureVerificationResult indicating success or failure
   */
  public verify(request: HttpRequest): SignatureVerificationResult {
    return this.signatureVerifier.verify(request);
  }

  /**
   * Verifies the signature and parses the webhook event from the incoming request.
   *
   * @param request The incoming HttpRequest
   * @returns WebhookEventParsingResult if valid, UnknownEvent or SignatureVerificationFailure otherwise
   */
  public verifyAndParseEvent(request: HttpRequest): WebhooksParsingResult {
    const verificationResult = this.verify(request);
    if (!verificationResult.success) {
      return verificationResult;
    }

    const requestBody = request.body;

    if (requestBody === undefined) {
      return createUnknownEvent('Missing request body');
    }
    if (requestBody.type !== 'text') {
      return createUnknownEvent('Invalid request body type');
    }

    try {
      const parsedRequestBody = JSONBig.parse(requestBody.content);

      const validationResult = validateAndMap(
        parsedRequestBody,
        webhooksEventParsingResultSchema
      );

      if (validationResult.errors) {
        return createUnknownEvent(requestBody.content);
      }

      return validationResult.result;
    } catch (error) {
      return createUnknownEvent(requestBody.content);
    }
  }
}
