/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isSignatureVerificationResult,
  SignatureVerificationFailure,
} from '../../core';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { WebhooksCEventParsingResult } from './webhooksCEventParsingResult';

/**
 * Union type representing all possible cases, handled by WebhooksC handler.
 */
export type WebhooksCParsingResult =
  | WebhooksCEventParsingResult
  | UnknownEvent
  | SignatureVerificationFailure;

export namespace WebhooksCParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: WebhooksCParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down the parsing result
   *
   * to a SignatureVerificationFailure type case.
   */
  export function isSignatureVerificationFailure(
    result: WebhooksCParsingResult
  ): result is SignatureVerificationFailure {
    return isSignatureVerificationResult(result) && result.success === false;
  }

  /**
   * Validation method to narrow down union type to StringEvent type case.
   */
  export function isStringEventEvent(
    result: WebhooksCParsingResult
  ): result is string {
    return WebhooksCEventParsingResult.isString(result);
  }

  /**
   * Validation method to narrow down union type to IntEvent type case.
   */
  export function isIntEventEvent(
    result: WebhooksCParsingResult
  ): result is number {
    return WebhooksCEventParsingResult.isNumber(result);
  }

  /**
   * Validation method to narrow down union type to NumberListEvent type case.
   */
  export function isNumberListEventEvent(
    result: WebhooksCParsingResult
  ): result is number[] {
    return WebhooksCEventParsingResult.isArrayOfNumber(result);
  }

  /**
   * Validation method to narrow down union type to StringMapEvent type case.
   */
  export function isStringMapEventEvent(
    result: WebhooksCParsingResult
  ): result is Record<string, string> {
    return WebhooksCEventParsingResult.isMapOfString(result);
  }
}
