/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  PaymentStatusCreatedEvent,
  paymentStatusCreatedEventSchema,
} from '../../models/paymentStatusCreatedEvent.js';
import {
  PaymentStatusUpdatedEvent,
  paymentStatusUpdatedEventSchema,
} from '../../models/paymentStatusUpdatedEvent.js';
import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';

/** This is a container type for one-of types. */
export type WebhooksAEventParsingResult =
  | PaymentStatusUpdatedEvent
  | PaymentStatusCreatedEvent;

export const webhooksAEventParsingResultSchema: Schema<WebhooksAEventParsingResult> = lazy(
  () =>
    oneOf([paymentStatusUpdatedEventSchema, paymentStatusCreatedEventSchema])
);

export namespace WebhooksAEventParsingResult {
  /**
   * Validation method to narrow down union type to PaymentStatusUpdatedEvent type case.
   *
   * Triggered when a payment status is updated via POST method
   */
  export function isPaymentStatusUpdatedEvent(
    value: unknown
  ): value is PaymentStatusUpdatedEvent {
    return isMappedValueValidForSchema(value, paymentStatusUpdatedEventSchema);
  }

  /**
   * Validation method to narrow down union type to PaymentStatusCreatedEvent type case.
   *
   * Triggered when a new payment status is created
   */
  export function isPaymentStatusCreatedEvent(
    value: unknown
  ): value is PaymentStatusCreatedEvent {
    return isMappedValueValidForSchema(value, paymentStatusCreatedEventSchema);
  }
}
