/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isSignatureVerificationResult,
  SignatureVerificationFailure,
} from '../../core';
import { PaymentStatusCreatedEvent } from '../../models/paymentStatusCreatedEvent';
import { PaymentStatusUpdatedEvent } from '../../models/paymentStatusUpdatedEvent';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { WebhooksAEventParsingResult } from './webhooksAEventParsingResult';

/**
 * Union type representing all possible cases, handled by WebhooksA handler.
 */
export type WebhooksAParsingResult =
  | WebhooksAEventParsingResult
  | UnknownEvent
  | SignatureVerificationFailure;

export namespace WebhooksAParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: WebhooksAParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down the parsing result
   *
   * to a SignatureVerificationFailure type case.
   */
  export function isSignatureVerificationFailure(
    result: WebhooksAParsingResult
  ): result is SignatureVerificationFailure {
    return isSignatureVerificationResult(result) && result.success === false;
  }

  /**
   * Validation method to narrow down union type to PaymentStatusUpdated type case.
   *
   * Triggered when a payment status is updated via POST method
   */
  export function isPaymentStatusUpdatedEvent(
    result: WebhooksAParsingResult
  ): result is PaymentStatusUpdatedEvent {
    return WebhooksAEventParsingResult.isPaymentStatusUpdatedEvent(result);
  }

  /**
   * Validation method to narrow down union type to PaymentStatusCreated type case.
   *
   * Triggered when a new payment status is created
   */
  export function isPaymentStatusCreatedEvent(
    result: WebhooksAParsingResult
  ): result is PaymentStatusCreatedEvent {
    return WebhooksAEventParsingResult.isPaymentStatusCreatedEvent(result);
  }
}
