/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuditLogEvent } from '../../models/auditLogEvent';
import { RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody } from '../../models/containers/rootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { WebhooksNoVerificationEventParsingResult } from './webhooksNoVerificationEventParsingResult';

/**
 * Union type representing all possible cases, handled by WebhooksNoVerification handler.
 */
export type WebhooksNoVerificationParsingResult =
  | WebhooksNoVerificationEventParsingResult
  | UnknownEvent;

export namespace WebhooksNoVerificationParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: WebhooksNoVerificationParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down union type to AuditLogEvent type case.
   *
   * Demonstrates an event without signature verification.
   */
  export function isAuditLogEventEvent(
    result: WebhooksNoVerificationParsingResult
  ): result is AuditLogEvent {
    return WebhooksNoVerificationEventParsingResult.isAuditLogEvent(result);
  }

  /**
   * Validation method to narrow down union type to RootLevelPrimitiveOneOfEvent type case.
   *
   * Root-level oneOf across primitives and collections of primitives/enums.
   */
  export function isRootLevelPrimitiveOneOfEventEvent(
    result: WebhooksNoVerificationParsingResult
  ): result is RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody {
    return WebhooksNoVerificationEventParsingResult.isRootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody(
      result
    );
  }
}
