/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  InventoryChangeEventBody,
  inventoryChangeEventBodySchema,
} from '../../models/containers/inventoryChangeEventBody.js';
import {
  SystemNotificationEventBody,
  systemNotificationEventBodySchema,
} from '../../models/containers/systemNotificationEventBody.js';
import {
  UserNotificationEventBody,
  userNotificationEventBodySchema,
} from '../../models/containers/userNotificationEventBody.js';
import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';

/** This is a container type for one-of types. */
export type WebhooksBEventParsingResult =
  | UserNotificationEventBody
  | SystemNotificationEventBody
  | InventoryChangeEventBody;

export const webhooksBEventParsingResultSchema: Schema<WebhooksBEventParsingResult> = lazy(
  () =>
    oneOf([
      userNotificationEventBodySchema,
      systemNotificationEventBodySchema,
      inventoryChangeEventBodySchema,
    ])
);

export namespace WebhooksBEventParsingResult {
  /**
   * Validation method to narrow down union type to UserNotificationEventBody type case.
   *
   * Triggered when user-related notifications occur
   */
  export function isUserNotificationEventBody(
    value: unknown
  ): value is UserNotificationEventBody {
    return isMappedValueValidForSchema(value, userNotificationEventBodySchema);
  }

  /**
   * Validation method to narrow down union type to SystemNotificationEventBody type case.
   *
   * Triggered when system-wide notifications occur
   */
  export function isSystemNotificationEventBody(
    value: unknown
  ): value is SystemNotificationEventBody {
    return isMappedValueValidForSchema(
      value,
      systemNotificationEventBodySchema
    );
  }

  /**
   * Validation method to narrow down union type to InventoryChangeEventBody type case.
   *
   * Triggered when inventory stock levels change
   */
  export function isInventoryChangeEventBody(
    value: unknown
  ): value is InventoryChangeEventBody {
    return isMappedValueValidForSchema(value, inventoryChangeEventBodySchema);
  }
}
