/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AuditLogEvent,
  auditLogEventSchema,
} from '../../models/auditLogEvent.js';
import {
  RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody,
  rootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBodySchema,
} from '../../models/containers/rootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody.js';
import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';

/** This is a container type for one-of types. */
export type WebhooksNoVerificationEventParsingResult =
  | AuditLogEvent
  | RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody;

export const webhooksNoVerificationEventParsingResultSchema: Schema<WebhooksNoVerificationEventParsingResult> = lazy(
  () =>
    oneOf([
      auditLogEventSchema,
      rootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBodySchema,
    ])
);

export namespace WebhooksNoVerificationEventParsingResult {
  /**
   * Validation method to narrow down union type to AuditLogEvent type case.
   *
   * Demonstrates an event without signature verification.
   */
  export function isAuditLogEvent(value: unknown): value is AuditLogEvent {
    return isMappedValueValidForSchema(value, auditLogEventSchema);
  }

  /**
   * Validation method to narrow down union type to RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody type case.
   *
   * Root-level oneOf across primitives and collections of primitives/enums.
   */
  export function isRootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody(
    value: unknown
  ): value is RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody {
    return isMappedValueValidForSchema(
      value,
      rootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBodySchema
    );
  }
}
