/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isSignatureVerificationResult,
  SignatureVerificationFailure,
} from '../../core';
import { OrderCreatedEvent } from '../../models/orderCreatedEvent';
import { OrderUpdatedEvent } from '../../models/orderUpdatedEvent';
import { PaymentCompletedEvent } from '../../models/paymentCompletedEvent';
import { PrimitiveCollectionEvent } from '../../models/primitiveCollectionEvent';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { WebhooksEventParsingResult } from './webhooksEventParsingResult';

/**
 * Union type representing all possible cases, handled by Webhooks handler.
 */
export type WebhooksParsingResult =
  | WebhooksEventParsingResult
  | UnknownEvent
  | SignatureVerificationFailure;

export namespace WebhooksParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: WebhooksParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down the parsing result
   *
   * to a SignatureVerificationFailure type case.
   */
  export function isSignatureVerificationFailure(
    result: WebhooksParsingResult
  ): result is SignatureVerificationFailure {
    return isSignatureVerificationResult(result) && result.success === false;
  }

  /**
   * Validation method to narrow down union type to OrderCreatedNewTestingMyNewyTesinggggggTocHejcjk type case.
   *
   * Triggered when a new order is created
   */
  export function isOrderCreatedNewTestingMyNewyTesinggggggTocHejcjkEvent(
    result: WebhooksParsingResult
  ): result is OrderCreatedEvent {
    return WebhooksEventParsingResult.isOrderCreatedEvent(result);
  }

  /**
   * Validation method to narrow down union type to OrderUpdated type case.
   *
   * Triggered when an order is updated
   */
  export function isOrderUpdatedEvent(
    result: WebhooksParsingResult
  ): result is OrderUpdatedEvent {
    return WebhooksEventParsingResult.isOrderUpdatedEvent(result);
  }

  /**
   * Validation method to narrow down union type to PaymentCompleted type case.
   *
   * Triggered when a payment is successfully processed
   */
  export function isPaymentCompletedEvent(
    result: WebhooksParsingResult
  ): result is PaymentCompletedEvent {
    return WebhooksEventParsingResult.isPaymentCompletedEvent(result);
  }

  /**
   * Validation method to narrow down union type to PrimitiveCollectionEvent type case.
   *
   * Demonstrates oneOf across enum(string), integer, and array types.
   */
  export function isPrimitiveCollectionEventEvent(
    result: WebhooksParsingResult
  ): result is PrimitiveCollectionEvent {
    return WebhooksEventParsingResult.isPrimitiveCollectionEvent(result);
  }
}
