/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  OrderCreatedEvent,
  orderCreatedEventSchema,
} from '../../models/orderCreatedEvent.js';
import {
  OrderUpdatedEvent,
  orderUpdatedEventSchema,
} from '../../models/orderUpdatedEvent.js';
import {
  PaymentCompletedEvent,
  paymentCompletedEventSchema,
} from '../../models/paymentCompletedEvent.js';
import {
  PrimitiveCollectionEvent,
  primitiveCollectionEventSchema,
} from '../../models/primitiveCollectionEvent.js';
import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';

/** This is a container type for one-of types. */
export type WebhooksEventParsingResult =
  | OrderCreatedEvent
  | OrderUpdatedEvent
  | PaymentCompletedEvent
  | PrimitiveCollectionEvent;

export const webhooksEventParsingResultSchema: Schema<WebhooksEventParsingResult> = lazy(
  () =>
    oneOf([
      orderCreatedEventSchema,
      orderUpdatedEventSchema,
      paymentCompletedEventSchema,
      primitiveCollectionEventSchema,
    ])
);

export namespace WebhooksEventParsingResult {
  /**
   * Validation method to narrow down union type to OrderCreatedEvent type case.
   *
   * Triggered when a new order is created
   */
  export function isOrderCreatedEvent(
    value: unknown
  ): value is OrderCreatedEvent {
    return isMappedValueValidForSchema(value, orderCreatedEventSchema);
  }

  /**
   * Validation method to narrow down union type to OrderUpdatedEvent type case.
   *
   * Triggered when an order is updated
   */
  export function isOrderUpdatedEvent(
    value: unknown
  ): value is OrderUpdatedEvent {
    return isMappedValueValidForSchema(value, orderUpdatedEventSchema);
  }

  /**
   * Validation method to narrow down union type to PaymentCompletedEvent type case.
   *
   * Triggered when a payment is successfully processed
   */
  export function isPaymentCompletedEvent(
    value: unknown
  ): value is PaymentCompletedEvent {
    return isMappedValueValidForSchema(value, paymentCompletedEventSchema);
  }

  /**
   * Validation method to narrow down union type to PrimitiveCollectionEvent type case.
   *
   * Demonstrates oneOf across enum(string), integer, and array types.
   */
  export function isPrimitiveCollectionEvent(
    value: unknown
  ): value is PrimitiveCollectionEvent {
    return isMappedValueValidForSchema(value, primitiveCollectionEventSchema);
  }
}
