/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateOrderRequest,
  createOrderRequestSchema,
} from '../models/createOrderRequest.js';
import { Order, orderSchema } from '../models/order.js';
import { BaseApi } from './baseApi.js';
import { CustomError } from '../errors/customError.js';

export class OrdersApi extends BaseApi {
  /**
   * Creates a new order and triggers callbacks for payment processing
   *
   * @param body
   * @return Response from the API call
   */
  async createOrder(
    body: CreateOrderRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Order>> {
    const req = this.createRequest('POST', '/orders');
    const mapped = req.prepareArgs({ body: [body, createOrderRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, CustomError, 'Invalid request');
    req.authenticate([{ apiKey: true }, { bearerAuth: true }]);
    return req.callAsJson(orderSchema, requestOptions);
  }
}
