/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

export const UnknownEventMarker = Symbol('UnknownEvent');

/**
 * Fallback type for unrecognized events.
 */
export interface UnknownEvent {
  [UnknownEventMarker]: true;
  body: unknown;
}

export function isUnknownEvent(event: unknown): event is UnknownEvent {
  return (
    typeof event === 'object' && event !== null && UnknownEventMarker in event
  );
}

export function createUnknownEvent(body: unknown): UnknownEvent {
  return {
    [UnknownEventMarker]: true,
    body,
  };
}
