/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EventType3, eventType3Schema } from './eventType3.js';

export interface AuditLogEvent {
  eventType?: EventType3;
  actor?: string;
  action?: string;
  context?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const auditLogEventSchema: Schema<AuditLogEvent> = typedExpandoObject(
  {
    eventType: ['eventType', optional(eventType3Schema)],
    actor: ['actor', optional(string())],
    action: ['action', optional(string())],
    context: ['context', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
