/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { OrderItem, orderItemSchema } from './orderItem.js';

export interface CreateOrderRequest {
  /** Unique identifier for the customer */
  customerId: string;
  items: OrderItem[];
  /** URL to receive callback notifications */
  callbackUrl: string;
  /** Binary file upload */
  document?: string;
  /** Additional order metadata */
  metadata?: unknown;
  attributes?: Record<string, string>;
  additionalProperties?: Record<string, unknown>;
}

export const createOrderRequestSchema: Schema<CreateOrderRequest> = lazy(() =>
  typedExpandoObject(
    {
      customerId: ['customerId', string()],
      items: ['items', array(orderItemSchema)],
      callbackUrl: ['callbackUrl', string()],
      document: ['document', optional(string())],
      metadata: ['metadata', optional(unknown())],
      attributes: ['attributes', optional(dict(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
