/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DeliveryDetails {
  method?: string;
  eta?: string;
  additionalProperties?: Record<string, unknown>;
}

export const deliveryDetailsSchema: Schema<DeliveryDetails> = typedExpandoObject(
  { method: ['method', optional(string())], eta: ['eta', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
