/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Status1, status1Schema } from './status1.js';

export interface EmailNotificationCallback {
  messageId?: string;
  recipientEmail?: string;
  status?: Status1;
  additionalProperties?: Record<string, unknown>;
}

export const emailNotificationCallbackSchema: Schema<EmailNotificationCallback> = typedExpandoObject(
  {
    messageId: ['messageId', optional(string())],
    recipientEmail: ['recipientEmail', optional(string())],
    status: ['status', optional(status1Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
