/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EventType
 */
export enum EventType {
  EnumOrderupdated = 'order.updated',
}

/**
 * Schema for EventType
 */
export const eventTypeSchema: Schema<EventType> = stringEnum(EventType);
