/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EventType3
 */
export enum EventType3 {
  EnumAuditlog = 'audit.log',
}

/**
 * Schema for EventType3
 */
export const eventType3Schema: Schema<EventType3> = stringEnum(EventType3);
