/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EventType1
 */
export enum EventType1 {
  EnumPaymentcompleted = 'payment.completed',
}

/**
 * Schema for EventType1
 */
export const eventType1Schema: Schema<EventType1> = stringEnum(EventType1);
