/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EventType2
 */
export enum EventType2 {
  EnumPrimitivevariant = 'primitive.variant',
}

/**
 * Schema for EventType2
 */
export const eventType2Schema: Schema<EventType2> = stringEnum(EventType2);
