/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Event
 */
export enum Event {
  EnumOrdercreated = 'order.created',
  EnumOrderupdated = 'order.updated',
  EnumOrdercancelled = 'order.cancelled',
  EnumPaymentcompleted = 'payment.completed',
  EnumPaymentfailed = 'payment.failed',
  EnumFulfillmentcompleted = 'fulfillment.completed',
}

/**
 * Schema for Event
 */
export const eventSchema: Schema<Event> = stringEnum(Event);
