/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FulfillmentStatuss
 */
export enum FulfillmentStatuss {
  Fulfilled = 'fulfilled',
  Failed = 'failed',
  Partial = 'partial',
}

/**
 * Schema for FulfillmentStatuss
 */
export const fulfillmentStatussSchema: Schema<FulfillmentStatuss> = stringEnum(
  FulfillmentStatuss
);
