/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FulfillmentStatus
 */
export enum FulfillmentStatus {
  Fulfilled = 'fulfilled',
  Failed = 'failed',
  Partial = 'partial',
}

/**
 * Schema for FulfillmentStatus
 */
export const fulfillmentStatusSchema: Schema<FulfillmentStatus> = stringEnum(
  FulfillmentStatus
);
