/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  dict,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';
import {
  FulfillmentCallbackDeliveryDetails,
  fulfillmentCallbackDeliveryDetailsSchema,
} from './containers/fulfillmentCallbackDeliveryDetails.js';
import {
  FulfillmentStatus,
  fulfillmentStatusSchema,
} from './fulfillmentStatus.js';
import {
  FulfillmentStatuss,
  fulfillmentStatussSchema,
} from './fulfillmentStatuss.js';
import {
  OauthScopeOauthACG,
  oauthScopeOauthACGSchema,
} from './oauthScopeOauthACG.js';
import { Package, packageSchema } from './package.js';

export interface FulfillmentCallback {
  orderId: string | null;
  fulfillmentStatus: FulfillmentStatus;
  trackingNumber?: string | null;
  carrier?: string;
  /** List of scopes that apply to the OAuth token */
  scopes?: OauthScopeOauthACG[] | null;
  estimatedDelivery?: string;
  timestamp?: string;
  /** Binary file upload */
  document?: string;
  totalWeight?: number;
  price?: number;
  quantity?: number;
  longId?: bigint;
  fragile?: boolean;
  /** Explicitly nullable field */
  notes?: string | null;
  items?: string[];
  packages?: Package[];
  address?: Address;
  metadata?: unknown;
  attributes?: Record<string, string>;
  deliveryDetails?: FulfillmentCallbackDeliveryDetails;
  orderIdd?: string | null;
  fulfillmentStatuss?: FulfillmentStatuss;
  trackingNumberr?: string | null;
  carrierr?: string;
  /** List of scopes that apply to the OAuth token */
  scopess?: OauthScopeOauthACG[] | null;
  estimatedDeliveryy?: string;
  timestampp?: string;
  /** Binary file upload */
  documentt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const fulfillmentCallbackSchema: Schema<FulfillmentCallback> = lazy(() =>
  typedExpandoObject(
    {
      orderId: ['orderId', nullable(string())],
      fulfillmentStatus: ['fulfillmentStatus', fulfillmentStatusSchema],
      trackingNumber: ['trackingNumber', optional(nullable(string()))],
      carrier: ['carrier', optional(string())],
      scopes: ['scopes', optional(nullable(array(oauthScopeOauthACGSchema)))],
      estimatedDelivery: ['estimatedDelivery', optional(string())],
      timestamp: ['timestamp', optional(string())],
      document: ['document', optional(string())],
      totalWeight: ['totalWeight', optional(number())],
      price: ['price', optional(number())],
      quantity: ['quantity', optional(number())],
      longId: ['longId', optional(bigint())],
      fragile: ['fragile', optional(boolean())],
      notes: ['notes', optional(nullable(string()))],
      items: ['items', optional(array(string()))],
      packages: ['packages', optional(array(packageSchema))],
      address: ['address', optional(addressSchema)],
      metadata: ['metadata', optional(unknown())],
      attributes: ['attributes', optional(dict(string()))],
      deliveryDetails: [
        'deliveryDetails',
        optional(fulfillmentCallbackDeliveryDetailsSchema),
      ],
      orderIdd: ['orderIdd', optional(nullable(string()))],
      fulfillmentStatuss: [
        'fulfillmentStatuss',
        optional(fulfillmentStatussSchema),
      ],
      trackingNumberr: ['trackingNumberr', optional(nullable(string()))],
      carrierr: ['carrierr', optional(string())],
      scopess: ['scopess', optional(nullable(array(oauthScopeOauthACGSchema)))],
      estimatedDeliveryy: ['estimatedDeliveryy', optional(string())],
      timestampp: ['timestampp', optional(string())],
      documentt: ['documentt', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
