/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InventoryStockDecreaseEvent {
  inventoryStockDecreaseEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const inventoryStockDecreaseEventSchema: Schema<InventoryStockDecreaseEvent> = typedExpandoObject(
  {
    inventoryStockDecreaseEventType: [
      'inventoryStockDecreaseEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
