/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InventoryStockDepletedEvent {
  inventoryStockDepletedEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const inventoryStockDepletedEventSchema: Schema<InventoryStockDepletedEvent> = typedExpandoObject(
  {
    inventoryStockDepletedEventType: [
      'inventoryStockDepletedEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
