/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface InventoryStockIncreaseEvent {
  inventoryStockIncreaseEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const inventoryStockIncreaseEventSchema: Schema<InventoryStockIncreaseEvent> = typedExpandoObject(
  {
    inventoryStockIncreaseEventType: [
      'inventoryStockIncreaseEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
