/**
 * Cypress Test APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Lion {
  id: string;
  type: string;
}

export const lionSchema: Schema<Lion> = object({
  id: ['id', string()],
  type: ['type', string()],
});
