/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface NotificationCallback {
  notificationType: string;
  subject: string;
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const notificationCallbackSchema: Schema<NotificationCallback> = typedExpandoObject(
  {
    notificationType: ['notificationType', string()],
    subject: ['subject', string()],
    message: ['message', string()],
  },
  'additionalProperties',
  optional(unknown())
);
