/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OauthScopeOauthACG
 */
export enum OauthScopeOauthACG {
  EnumFileRequestsread = 'file_requests.read',
  Zahra = 'zahra',
  Test1 = 'test1',
  Selection = 'selection',
}

/**
 * Schema for OauthScopeOauthACG
 */
export const oauthScopeOauthACGSchema: Schema<OauthScopeOauthACG> = stringEnum(
  OauthScopeOauthACG
);
