/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { OrderItem, orderItemSchema } from './orderItem.js';
import { Status, statusSchema } from './status.js';

export interface Order {
  orderId?: string;
  customerId?: string;
  items?: OrderItem[];
  totalAmount?: number;
  status?: Status;
  createdAt?: string;
  updatedAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const orderSchema: Schema<Order> = lazy(() =>
  typedExpandoObject(
    {
      orderId: ['orderId', optional(string())],
      customerId: ['customerId', optional(string())],
      items: ['items', optional(array(orderItemSchema))],
      totalAmount: ['totalAmount', optional(number())],
      status: ['status', optional(statusSchema)],
      createdAt: ['createdAt', optional(string())],
      updatedAt: ['updatedAt', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
