/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EventType, eventTypeSchema } from './eventType.js';

export interface OrderUpdatedEvent {
  eventType?: EventType;
  orderUpdatedId: number;
  additionalProperties?: Record<string, unknown>;
}

export const orderUpdatedEventSchema: Schema<OrderUpdatedEvent> = typedExpandoObject(
  {
    eventType: ['eventType', optional(eventTypeSchema)],
    orderUpdatedId: ['orderUpdatedId', number()],
  },
  'additionalProperties',
  optional(unknown())
);
