/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OrderItem {
  productId: string;
  quantity: number;
  price: number;
  description?: string;
  additionalProperties?: Record<string, unknown>;
}

export const orderItemSchema: Schema<OrderItem> = typedExpandoObject(
  {
    productId: ['productId', string()],
    quantity: ['quantity', number()],
    price: ['price', number()],
    description: ['description', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
