/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Package {
  packageId?: string;
  weight?: number;
  additionalProperties?: Record<string, unknown>;
}

export const packageSchema: Schema<Package> = typedExpandoObject(
  {
    packageId: ['packageId', optional(string())],
    weight: ['weight', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
