/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PaymentStatusCreatedEvent {
  paymentStatusCreatedId: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentStatusCreatedEventSchema: Schema<PaymentStatusCreatedEvent> = typedExpandoObject(
  { paymentStatusCreatedId: ['paymentStatusCreatedId', string()] },
  'additionalProperties',
  optional(unknown())
);
