/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentStatus, paymentStatusSchema } from './paymentStatus.js';

export interface PaymentCallback {
  orderId: string;
  paymentStatus: PaymentStatus;
  transactionId: string;
  amount?: number;
  currency?: string;
  timestamp?: string;
  /** Reason for payment failure (if applicable) */
  failureReason?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentCallbackSchema: Schema<PaymentCallback> = typedExpandoObject(
  {
    orderId: ['orderId', string()],
    paymentStatus: ['paymentStatus', paymentStatusSchema],
    transactionId: ['transactionId', string()],
    amount: ['amount', optional(number())],
    currency: ['currency', optional(string())],
    timestamp: ['timestamp', optional(string())],
    failureReason: ['failureReason', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
