/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PaymentStatusUpdatedEvent {
  paymentStatusId: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentStatusUpdatedEventSchema: Schema<PaymentStatusUpdatedEvent> = typedExpandoObject(
  { paymentStatusId: ['paymentStatusId', string()] },
  'additionalProperties',
  optional(unknown())
);
