/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentStatus
 */
export enum PaymentStatus {
  Success = 'success',
  Failed = 'failed',
  Pending = 'pending',
}

/**
 * Schema for PaymentStatus
 */
export const paymentStatusSchema: Schema<PaymentStatus> = stringEnum(
  PaymentStatus
);
