/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EventType1, eventType1Schema } from './eventType1.js';

export interface PaymentCompletedEvent {
  eventType?: EventType1;
  paymentId: number;
  additionalProperties?: Record<string, unknown>;
}

export const paymentCompletedEventSchema: Schema<PaymentCompletedEvent> = typedExpandoObject(
  {
    eventType: ['eventType', optional(eventType1Schema)],
    paymentId: ['paymentId', number()],
  },
  'additionalProperties',
  optional(unknown())
);
