/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { EventType2, eventType2Schema } from './eventType2.js';

export interface PrimitiveCollectionEvent {
  eventType?: EventType2;
  ids: number[];
  additionalProperties?: Record<string, unknown>;
}

export const primitiveCollectionEventSchema: Schema<PrimitiveCollectionEvent> = typedExpandoObject(
  {
    eventType: ['eventType', optional(eventType2Schema)],
    ids: ['ids', array(number())],
  },
  'additionalProperties',
  optional(unknown())
);
