/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RootLevelPrimitiveOneOfEventRequest
 */
export enum RootLevelPrimitiveOneOfEventRequest {
  On = 'on',
  Off = 'off',
  Pending = 'pending',
}

/**
 * Schema for RootLevelPrimitiveOneOfEventRequest
 */
export const rootLevelPrimitiveOneOfEventRequestSchema: Schema<RootLevelPrimitiveOneOfEventRequest> = stringEnum(
  RootLevelPrimitiveOneOfEventRequest
);
