/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RootLevelPrimitiveOneOfEventRequest1
 */
export enum RootLevelPrimitiveOneOfEventRequest1 {
  Alpha = 'alpha',
  Beta = 'beta',
  Gamma = 'gamma',
}

/**
 * Schema for RootLevelPrimitiveOneOfEventRequest1
 */
export const rootLevelPrimitiveOneOfEventRequest1Schema: Schema<RootLevelPrimitiveOneOfEventRequest1> = stringEnum(
  RootLevelPrimitiveOneOfEventRequest1
);
