/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Status2, status2Schema } from './status2.js';

export interface SmsNotificationCallback {
  messageId?: string;
  phoneNumber?: string;
  status?: Status2;
  additionalProperties?: Record<string, unknown>;
}

export const smsNotificationCallbackSchema: Schema<SmsNotificationCallback> = typedExpandoObject(
  {
    messageId: ['messageId', optional(string())],
    phoneNumber: ['phoneNumber', optional(string())],
    status: ['status', optional(status2Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
