/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status2
 */
export enum Status2 {
  Delivered = 'delivered',
  Failed = 'failed',
}

/**
 * Schema for Status2
 */
export const status2Schema: Schema<Status2> = stringEnum(Status2);
