/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SystemMaintenanceNotificationEvent {
  systemMaintenanceNotificationEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const systemMaintenanceNotificationEventSchema: Schema<SystemMaintenanceNotificationEvent> = typedExpandoObject(
  {
    systemMaintenanceNotificationEventType: [
      'systemMaintenanceNotificationEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
