/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SystemAlertNotificationEvent {
  systemAlertNotificationEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const systemAlertNotificationEventSchema: Schema<SystemAlertNotificationEvent> = typedExpandoObject(
  {
    systemAlertNotificationEventType: [
      'systemAlertNotificationEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
