/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SystemPerformanceNotificationEvent {
  systemPerformanceNotificationEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const systemPerformanceNotificationEventSchema: Schema<SystemPerformanceNotificationEvent> = typedExpandoObject(
  {
    systemPerformanceNotificationEventType: [
      'systemPerformanceNotificationEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
