/**
 * Cypress Test APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema } from '../schema.js';
import {
  OAuthScopeOAuthACGEnum,
  oAuthScopeOAuthACGEnumSchema,
} from './oAuthScopeOAuthACGEnum.js';

export interface TokensRequest {
  /** List of scopes that apply to the OAuth token */
  scopes: OAuthScopeOAuthACGEnum[];
}

export const tokensRequestSchema: Schema<TokensRequest> = object({
  scopes: ['scopes', array(oAuthScopeOAuthACGEnumSchema)],
});
