/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UserPreferenceNotificationEvent {
  userPreferenceNotificationEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const userPreferenceNotificationEventSchema: Schema<UserPreferenceNotificationEvent> = typedExpandoObject(
  {
    userPreferenceNotificationEventType: [
      'userPreferenceNotificationEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
