/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UserActionNotificationEvent {
  userActionNotificationEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const userActionNotificationEventSchema: Schema<UserActionNotificationEvent> = typedExpandoObject(
  {
    userActionNotificationEventType: [
      'userActionNotificationEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
