/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UserStatusNotificationEvent {
  userStatusNotificationEventType: string;
  additionalProperties?: Record<string, unknown>;
}

export const userStatusNotificationEventSchema: Schema<UserStatusNotificationEvent> = typedExpandoObject(
  {
    userStatusNotificationEventType: [
      'userStatusNotificationEventType',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
