/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Event, eventSchema } from './event.js';

export interface WebhookRegistration {
  /** The endpoint URL that will receive webhook events */
  url: string;
  /** List of events to subscribe to */
  events: Event[];
  /** Secret key for webhook signature verification */
  secret?: string;
  /** Whether the webhook is active */
  active?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const webhookRegistrationSchema: Schema<WebhookRegistration> = typedExpandoObject(
  {
    url: ['url', string()],
    events: ['events', array(eventSchema)],
    secret: ['secret', optional(string())],
    active: ['active', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
