/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface WebhookUpdate {
  url?: string;
  events?: string[];
  secret?: string;
  active?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const webhookUpdateSchema: Schema<WebhookUpdate> = typedExpandoObject(
  {
    url: ['url', optional(string())],
    events: ['events', optional(array(string()))],
    secret: ['secret', optional(string())],
    active: ['active', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
