/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Webhook {
  webhookId?: string;
  createdAt?: string;
  updatedAt?: string;
  /** Timestamp of the last successful delivery */
  lastDelivery?: string;
  /** Total number of events delivered */
  deliveryCount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const webhookSchema: Schema<Webhook> = typedExpandoObject(
  {
    webhookId: ['webhookId', optional(string())],
    createdAt: ['createdAt', optional(string())],
    updatedAt: ['updatedAt', optional(string())],
    lastDelivery: ['lastDelivery', optional(string())],
    deliveryCount: ['deliveryCount', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
