/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  NotificationCallback,
  notificationCallbackSchema,
} from '../../models/notificationCallback.js';
import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';

/** This is a container type for one-of types. */
export type CallbacksBEventParsingResult = NotificationCallback;

const discriminatorMap = {
  'email': notificationCallbackSchema,
  'sms': notificationCallbackSchema,
};

export const callbacksBEventParsingResultSchema: Schema<CallbacksBEventParsingResult> = lazy(
  () =>
    oneOf([notificationCallbackSchema], discriminatorMap, 'notificationType')
);

export namespace CallbacksBEventParsingResult {
  /**
   * Validation method to narrow down union type to NotificationCallback type case.
   *
   * Called when email notification delivery is complete
   */
  export function isNotificationCallback(
    value: unknown
  ): value is NotificationCallback {
    return isMappedValueValidForSchema(value, notificationCallbackSchema);
  }
}
