/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  FulfillmentCallback,
  fulfillmentCallbackSchema,
} from '../../models/fulfillmentCallback.js';
import {
  PaymentCallback,
  paymentCallbackSchema,
} from '../../models/paymentCallback.js';
import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';

/** This is a container type for one-of types. */
export type CallbacksAEventParsingResult =
  | PaymentCallback
  | FulfillmentCallback;

export const callbacksAEventParsingResultSchema: Schema<CallbacksAEventParsingResult> = lazy(
  () => oneOf([paymentCallbackSchema, fulfillmentCallbackSchema])
);

export namespace CallbacksAEventParsingResult {
  /**
   * Validation method to narrow down union type to PaymentCallback type case.
   *
   * Called when payment processing is complete
   */
  export function isPaymentCallback(value: unknown): value is PaymentCallback {
    return isMappedValueValidForSchema(value, paymentCallbackSchema);
  }

  /**
   * Validation method to narrow down union type to FulfillmentCallback type case.
   *
   * Called when order processing is complete
   */
  export function isFulfillmentCallback(
    value: unknown
  ): value is FulfillmentCallback {
    return isMappedValueValidForSchema(value, fulfillmentCallbackSchema);
  }
}
