/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isSignatureVerificationResult,
  SignatureVerificationFailure,
} from '../../core';
import { FulfillmentCallback } from '../../models/fulfillmentCallback';
import { PaymentCallback } from '../../models/paymentCallback';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { CallbacksAEventParsingResult } from './callbacksAEventParsingResult';

/**
 * Union type representing all possible cases, handled by CallbacksA handler.
 */
export type CallbacksAParsingResult =
  | CallbacksAEventParsingResult
  | UnknownEvent
  | SignatureVerificationFailure;

export namespace CallbacksAParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: CallbacksAParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down the parsing result
   *
   * to a SignatureVerificationFailure type case.
   */
  export function isSignatureVerificationFailure(
    result: CallbacksAParsingResult
  ): result is SignatureVerificationFailure {
    return isSignatureVerificationResult(result) && result.success === false;
  }

  /**
   * Validation method to narrow down union type to PaymentCallback type case.
   *
   * Called when payment processing is complete
   */
  export function isPaymentCallbackEvent(
    result: CallbacksAParsingResult
  ): result is PaymentCallback {
    return CallbacksAEventParsingResult.isPaymentCallback(result);
  }

  /**
   * Validation method to narrow down union type to FulfillmentCallback type case.
   *
   * Called when order processing is complete
   */
  export function isFulfillmentCallbackEvent(
    result: CallbacksAParsingResult
  ): result is FulfillmentCallback {
    return CallbacksAEventParsingResult.isFulfillmentCallback(result);
  }
}
