/**
 * Webhooks and Callbacks APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isSignatureVerificationResult,
  SignatureVerificationFailure,
} from '../../core';
import { NotificationCallback } from '../../models/notificationCallback';
import { isUnknownEvent, UnknownEvent } from '../unknownEvent';
import { CallbacksBEventParsingResult } from './callbacksBEventParsingResult';

/**
 * Union type representing all possible cases, handled by CallbacksB handler.
 */
export type CallbacksBParsingResult =
  | CallbacksBEventParsingResult
  | UnknownEvent
  | SignatureVerificationFailure;

export namespace CallbacksBParsingResult {
  /**
   * Validation method to narrow down the parsing result
   *
   * to an UnknownEvent type case.
   */
  export function isEventTypeUnknown(
    result: CallbacksBParsingResult
  ): result is UnknownEvent {
    return isUnknownEvent(result);
  }

  /**
   * Validation method to narrow down the parsing result
   *
   * to a SignatureVerificationFailure type case.
   */
  export function isSignatureVerificationFailure(
    result: CallbacksBParsingResult
  ): result is SignatureVerificationFailure {
    return isSignatureVerificationResult(result) && result.success === false;
  }

  /**
   * Validation method to narrow down union type to EmailNotificationCallback type case.
   *
   * Called when email notification delivery is complete
   */
  export function isEmailNotificationCallbackEvent(
    result: CallbacksBParsingResult
  ): result is NotificationCallback {
    return CallbacksBEventParsingResult.isNotificationCallback(result);
  }

  /**
   * Validation method to narrow down union type to SmsNotificationCallback type case.
   *
   * Called when SMS notification delivery is complete
   */
  export function isSmsNotificationCallbackEvent(
    result: CallbacksBParsingResult
  ): result is NotificationCallback {
    return CallbacksBEventParsingResult.isNotificationCallback(result);
  }
}
